### ISSUE TITLE
Extract error

### ISSUE THREAD

**Issue by Sekilsgs2** [fpv-wtf/ar-firmware-tools#1]
Hi - i'm try extract avatar firmware but always geting same errors - 

Error
    at new KaitaiStream.EOFError (/home/sekil/otr/ar-firmware-tools/node_modules/kaitai-struct/KaitaiStream.js:723:17)
    at KaitaiStream.ensureBytesLeft (/home/sekil/otr/ar-firmware-tools/node_modules/kaitai-struct/KaitaiStream.js:811:11)
    at KaitaiStream.mapUint8Array (/home/sekil/otr/ar-firmware-tools/node_modules/kaitai-struct/KaitaiStream.js:827:8)
    at KaitaiStream.readBytes (/home/sekil/otr/ar-firmware-tools/node_modules/kaitai-struct/KaitaiStream.js:500:15)
    at Otra._read (/home/sekil/otr/ar-firmware-tools/otra_reader/Otra.js:28:25)
    at new Otra (/home/sekil/otr/ar-firmware-tools/otra_reader/Otra.js:18:10)
    at Object.handler (/home/sekil/otr/ar-firmware-tools/otra.js:87:24)
    at /home/sekil/otr/ar-firmware-tools/node_modules/yargs/build/index.cjs:1:8891
    at j (/home/sekil/otr/ar-firmware-tools/node_modules/yargs/build/index.cjs:1:4956)
    at M.handleValidationAndGetResult (/home/sekil/otr/ar-firmware-tools/node_modules/yargs/build/index.cjs:1:8860) {
  message: 'requested 4765772 bytes, but only 4765516 bytes available',
  bytesReq: 4765772,
  bytesAvail: 4765516
}

How i'm can fix this?

**Comment by j005u** [comment]
This happens because the baseband RTOS is a (big) v1 OTRA image internally which contains the entire baseband in the OTRA rom section. The current Kaitai definition is flawed as it treats the rom section as a fixed blob that gets loaded into memory at all times. In contrast to all the other large images that are sections in OTRA v4 images, which are treated correctly and streamed, instead of being loaded into memory all at once.

I need to re-factor the Kaitai definition to stream the rom section like v4 images are handled.

Meanwhile you can:

- Ignore the error if you don't care about the baseband RTOS image, the script should proceed and extract everything else properly
- Try setting a larger memory limit for node while running the extraction script. eg:

```
NODE_OPTIONS=--max-old-space-size=8192 scripts/avatar_extract.sh Avatar_Gnd_23.23.4.img
```

Leaving this issue open until I have a proper fix for the Kaitai definitions in place. PR welcome if you can be bothered to do this.

**Comment by j005u** [comment]
Turns out this had nothing to do with memory exhaustion, a7_rtos.img is a different ARTO format altogether.

Fixed with latest commit by implementing said format along with a few other fixes.
